name: Generate a build and push to another branch

on:
  push:
    branches:
      - master # La rama en la que realizas los nuevos cambios

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # El comando de build de tu proyecto

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to another branch
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Mubel77/jbindustrialgroup.git
          git add .
          git commit -m "Build: ${{ github.sha }}"
          git push origin master # Cambia a la rama donde quieras hacer el push
