name: Generate a build and push to another branch

on:
  push:
    branches:
      - master # La rama en la que realizas los nuevos cambios

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # El comando de build de tu proyecto

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to another branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: master  # Cambia esto a la rama donde quieras hacer el push
          FOLDER: dist # El directorio donde se generan los assets
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Aquí usas el token que configuraste como secreto
          MESSAGE: "Build: ({sha}) {msg}" # El mensaje de commit
